import { IHistoryItem } from 'types/historyItem';

export const HISTORY_MOCK: IHistoryItem[] = [
	{
		id: '04e16f3f-8c2e-4f51-bffd-6ds5afb954d6b3',
		name: 'ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaa3a aaaaaaaaaaaj',
		type: '',
		view: '',
		factoryNumber: '897799',
		verificationControlInStateRegister: false,
		inventoryNumber: '',
		division: '',
		responsible: '',
		location:
			'ГОСТ rrrrr-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		verificationDate: '2024-06-25T21:00:00.000Z',
		dateOfTheNextVerification: '2024-06-25T21:00:00.000Z',
		typeOfWork: '',
		suitability: 'false',
		condition:
			'Некоторые документы, например, уведомления об отпуске, мы отправляем с большим запасом (поскольку есть такая возможность) и сотрудники могут подписать их в течение 2-3 дней. В исключительных случаях, когда сотрудники находятся на больничных или в фактическ',
		stateRegister: '',
		certificate: '',
		fgisUrl: '',
		productionDate: '2024-06-25T21:00:00.000Z',
		organization: '',
		accuracyClass: '',
		interVerificationInterval: 1,
		measurementLimit: '',
		additionalData:
			'ГkОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		size: 'большой',
		methodology: '',
		cost: '0.00',
		notes: 'ГОСpТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		userIds: [],
		editedBy: 'Петр Последний',
		modificationDate: '2024-06-25T21:00:00.000Z',
		action: 'Создание',
		flags: {
			id: 'create',
			name: 'create',
			type: 'create',
			view: 'create',
			factoryNumber: 'create',
			verificationControlInStateRegister: 'create',
			inventoryNumber: 'create',
			division: 'create',
			responsible: 'create',
			location: 'create',
			verificationDate: 'create',
			dateOfTheNextVerification: 'create',
			typeOfWork: 'create',
			suitability: 'create',
			condition: 'create',
			stateRegister: 'create',
			certificate: 'create',
			fgisUrl: 'create',
			productionDate: 'create',
			organization: 'create',
			accuracyClass: 'create',
			interVerificationInterval: 'create',
			measurementLimit: 'create',
			additionalData: 'create',
			size: 'create',
			methodology: 'create',
			cost: 'create',
			notes: 'create',
		},
	},
	{
		id: '04e16f3f-8c2e-4f51-bffd-6d5afb954d6b3',
		name: 'Новое какое то наименование',
		type: '',
		view: 'Новый какой то вид',
		factoryNumber: '897799',
		verificationControlInStateRegister: false,
		inventoryNumber: '',
		division: '',
		responsible: '',
		location: 'Новое местоположение',
		verificationDate: '2024-06-25T21:00:00.000Z',
		dateOfTheNextVerification: '2024-06-25T21:00:00.000Z',
		typeOfWork: '',
		suitability: 'false',
		condition:
			'Некоторые документы, например, уведомления об отпуске, мы отправляем с большим запасом (поскольку есть такая возможность) и сотрудники могут подписать их в течение 2-3 дней. В исключительных случаях, когда сотрудники находятся на больничных или в фактическ',
		stateRegister: '',
		certificate: '',
		fgisUrl: '',
		productionDate: '2024-06-25T21:00:00.000Z',
		organization: '',
		accuracyClass: '',
		interVerificationInterval: 1,
		measurementLimit: '',
		additionalData:
			'ГkОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		size: 'большой',
		methodology: '',
		cost: '0.00',
		notes: 'ГОСpТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		userIds: [],
		editedBy: 'Петр Последний',
		modificationDate: '2024-06-25T21:00:00.000Z',
		action: 'Редактирование',
		flags: {
			id: 'create',
			name: 'update',
			type: 'create',
			view: 'update',
			factoryNumber: 'create',
			verificationControlInStateRegister: 'create',
			inventoryNumber: 'create',
			division: 'create',
			responsible: 'create',
			location: 'update',
			verificationDate: 'create',
			dateOfTheNextVerification: 'create',
			typeOfWork: 'create',
			suitability: 'create',
			condition: 'create',
			stateRegister: 'update',
			certificate: 'create',
			fgisUrl: 'create',
			productionDate: 'create',
			organization: 'create',
			accuracyClass: 'create',
			interVerificationInterval: 'create',
			measurementLimit: 'create',
			additionalData: 'update',
			size: 'create',
			methodology: 'create',
			cost: 'create',
			notes: 'create',
		},
	},
	{
		id: '04e16f3f-8c2e-4f51-bffd-6d5afb9f54d6b3',
		name: 'Новое какое то наименование',
		type: '',
		view: 'Новый какой то вид',
		factoryNumber: '897799',
		verificationControlInStateRegister: false,
		inventoryNumber: '',
		division: '',
		responsible: '',
		location: 'Новое местоположение',
		verificationDate: '2024-06-25T21:00:00.000Z',
		dateOfTheNextVerification: '2024-06-25T21:00:00.000Z',
		typeOfWork: '',
		suitability: 'false',
		condition:
			'Некоторые документы, например, уведомления об отпуске, мы отправляем с большим запасом (поскольку есть такая возможность) и сотрудники могут подписать их в течение 2-3 дней. В исключительных случаях, когда сотрудники находятся на больничных или в фактическ',
		stateRegister: '',
		certificate: '',
		fgisUrl: '',
		productionDate: '2024-06-25T21:00:00.000Z',
		organization: '',
		accuracyClass: '',
		interVerificationInterval: 1,
		measurementLimit: '',
		additionalData:
			'ГkОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		size: 'большой',
		methodology: '',
		cost: '0.00',
		notes: 'ГОСpТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaa',
		userIds: [],
		editedBy: 'Петр Последний',
		modificationDate: '2024-06-25T21:00:00.000Z',
		action: 'Удаление',
		flags: {
			id: 'create',
			name: 'update',
			type: 'create',
			view: 'update',
			factoryNumber: 'create',
			verificationControlInStateRegister: 'create',
			inventoryNumber: 'create',
			division: 'create',
			responsible: 'create',
			location: 'update',
			verificationDate: 'create',
			dateOfTheNextVerification: 'create',
			typeOfWork: 'create',
			suitability: 'create',
			condition: 'create',
			stateRegister: 'update',
			certificate: 'create',
			fgisUrl: 'create',
			productionDate: 'create',
			organization: 'create',
			accuracyClass: 'create',
			interVerificationInterval: 'create',
			measurementLimit: 'create',
			additionalData: 'update',
			size: 'create',
			methodology: 'create',
			cost: 'create',
			notes: 'create',
		},
	},
	{
		id: '1aa370ff-6e99-4af7-9a70-b2a22c12d863',
		name: 'ГОСТ 8.557-2007 ГСИ. Государственная поверочная схема для средств измерений спектральных, интегральных и редуцированных коэффициентов направленного пропускания и оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaaj',
		type: '',
		view: '',
		factoryNumber: '',
		verificationControlInStateRegister: false,
		inventoryNumber: '',
		division: '',
		responsible: '',
		location: '',
		verificationDate: '2024-07-08T21:00:00.000Z',
		dateOfTheNextVerification: '2024-07-08T21:00:00.000Z',
		typeOfWork: '',
		suitability: 'false',
		condition: '',
		stateRegister: '',
		certificate: '',
		fgisUrl: '',
		productionDate: '2024-07-08T21:00:00.000Z',
		organization: '',
		accuracyClass: '',
		interVerificationInterval: 1,
		measurementLimit: '',
		additionalData: '',
		size: 'маленький',
		methodology: '',
		cost: '0.00',
		notes: '',
		userIds: [],
		editedBy: 'Петр Первый',
		modificationDate: '2024-06-25T21:00:00.000Z',
		action: 'Удаление',
		flags: {
			id: 'create',
			name: 'create',
			type: 'create',
			view: 'create',
			factoryNumber: 'create',
			verificationControlInStateRegister: 'create',
			inventoryNumber: 'create',
			division: 'create',
			responsible: 'create',
			location: 'create',
			verificationDate: 'create',
			dateOfTheNextVerification: 'create',
			typeOfWork: 'create',
			suitability: 'create',
			condition: 'create',
			stateRegister: 'create',
			certificate: 'create',
			fgisUrl: 'create',
			productionDate: 'create',
			organization: 'create',
			accuracyClass: 'create',
			interVerificationInterval: 'create',
			measurementLimit: 'create',
			additionalData: 'create',
			size: 'create',
			methodology: 'create',
			cost: 'create',
			notes: 'create',
		},
	},
	{
		id: '1aa370ff-6e99-4af7-9a70-b2a22c1s2d863',
		name: 'ГОСТ 8.557-2007 ГСИ. Государственная оптической плотности в диапазоне длин волн от 0,2 до 50,0 мкм, диффузного и зеркального отражений в диапазоне длин волн от 0,2 до 20,0 мкм Фотометры выполнены в виде малогабаритного настольного, переносного прибора, состоящего из измерительного дреобразователя и фотометрической ячейки со сменными источниками излучения aaaaaaaaaaaaaaaaa aaaaaaaaaaaj',
		type: '',
		view: '',
		factoryNumber: '',
		verificationControlInStateRegister: false,
		inventoryNumber: '',
		division: '',
		responsible: '',
		location: '',
		verificationDate: '2024-07-08T21:00:00.000Z',
		dateOfTheNextVerification: '2024-07-08T21:00:00.000Z',
		typeOfWork: '',
		suitability: 'false',
		condition: '',
		stateRegister: '',
		certificate: '',
		fgisUrl: '',
		productionDate: '2024-07-08T21:00:00.000Z',
		organization: '',
		accuracyClass: '',
		interVerificationInterval: 1,
		measurementLimit: '',
		additionalData: '',
		size: 'маленький',
		methodology: '',
		cost: '0.00',
		notes: '',
		userIds: [],
		editedBy: 'Гомер Симпсон',
		modificationDate: '2024-06-25T21:00:00.000Z',
		action: 'Редактирование',
		flags: {
			id: 'create',
			name: 'update',
			type: 'remove',
			view: 'create',
			factoryNumber: 'remove',
			verificationControlInStateRegister: 'create',
			inventoryNumber: 'create',
			division: 'create',
			responsible: 'create',
			location: 'create',
			verificationDate: 'create',
			dateOfTheNextVerification: 'create',
			typeOfWork: 'create',
			suitability: 'create',
			condition: 'create',
			stateRegister: 'create',
			certificate: 'create',
			fgisUrl: 'create',
			productionDate: 'create',
			organization: 'create',
			accuracyClass: 'create',
			interVerificationInterval: 'create',
			measurementLimit: 'create',
			additionalData: 'create',
			size: 'create',
			methodology: 'create',
			cost: 'create',
			notes: 'create',
		},
	},
];
